### ISSUE TITLE
Chore: Run API Tests against Review APP

### ISSUE THREAD

**Issue by nelsonic** [dwyl/mvp#315]
As noted in https://github.com/dwyl/mvp/issues/297 the `API` Tests are failing on `main` 😢 
This is due to the `REQUEST_ERROR connect ECONNREFUSED ::1:4000` i.e. `GitHub Actions` blocking the requests. 

We need to investigate if a `GitHub Action` can make an outbound HTTP Request to an external URL/Endpoint.

> **Note**: I suspect that outbound HTTP Requests might be blocked to avoid abuse. 🤷‍♂️ 

If it's _possible_ make outbound HTTP Requests, then we should attempt to run them agains the Review App. 
The [`github/scripts/review-apps.sh`](https://github.com/dwyl/mvp/blob/main/.github/scripts/review-apps.sh#L5) can be used as the basis for deriving the Review App URL:
https://github.com/dwyl/mvp/blob/cd0b132489e55948d21f32ca9250adf494e6b8fe/.github/scripts/review-apps.sh#L5

Then we just have to use that URL for the API tests. 🤞 

# Todo 

+ [ ] Investigate if `GitHub Actions` can make outbound HTTP/REST requests. 🔍

**Comment by nelsonic** [comment]
It _appears_ to be possible to make outbound HTTP Requests: https://github.com/marketplace/actions/http-request-action
@LuchoTurtle would you mind investigating this further? 🔍 🙏 
Specifically: please create a script that makes an HTTP Request to a known URL e.g. the MVP API. 🌎 
Log everything you try in this issue thread. 📝

**Comment by LuchoTurtle** [comment]
Continuing on from: https://github.com/dwyl/mvp/issues/297#issuecomment-1439919391

Running against the MVp that is deployed as a review app on `fly.io`. 
Almost all tests run, save for a few - which doesn't really add up.

<img width="636" alt="image" src="https://user-images.githubusercontent.com/17494745/220620215-273fecbb-b3fd-4687-b873-eedc10fe67c4.png">

I still need to:
- [ ]  change the `fly_dev.json` to have the correct review app URL.

**Comment by LuchoTurtle** [comment]
I think this is because `seeds.exs` is not being run on the `review app` deployment phase.
Nelson's asked this before https://community.fly.io/t/how-to-run-seeds-exs-for-elixir-phoenix-app/3591/10

The overall accepted answer would involve creating a module and connecting to the Fly.io instance through SSL an run the `IEX` command there. I don't know if that's doable on a github action workflow, though 🤔

**Comment by nelsonic** [comment]
Connecting via SSH is a wild goose chase. Don’t waste your time. Please just open a separate issue for creating test data. 🙏

**Comment by nelsonic** [comment]
@LuchoTurtle did you read: https://community.fly.io/t/how-to-run-seeds-exs-for-elixir-phoenix-app/3591/6 ? 🤷‍♂️ 
This is how we are doing it in `auth` and it works fine. 

In `seeds.exs` it's pretty clear that this won't run anywhere other than `Mix.env() == :dev` ...

https://github.com/dwyl/mvp/blob/cd0b132489e55948d21f32ca9250adf494e6b8fe/priv/repo/seeds.exs#L12-L19

i.e. because the Review App is `Mix.env() == :prod` no records will be inserted.

**Comment by LuchoTurtle** [comment]
Yes, I've read it and hence why I though that, since `Mix.env() == :prod`, it perhaps would be useful to try to set an env variable that is only run in production that toggles the execution of `seeds`.

https://blog.miguelcoba.com/preparing-a-phoenix-16-app-for-deployment-with-elixir-releases

However, because of https://github.com/dwyl/mvp/issues/297#issuecomment-1441137816, I won't pursue this route.
