### ISSUE TITLE
Chore/Bug: Running Timer [Elapsed Time] does not update when `timer.start` is updated

### ISSUE THREAD

**Issue by nelsonic** [dwyl/mvp#374]
As noted in https://github.com/dwyl/mvp/pull/372 the `timer` displayed in the interface does not update when the `timer.start` is updated. A _manual_ refresh is required: 

https://github.com/dwyl/mvp/assets/194400/f1d0a0c8-471e-452a-a74e-4aed3a59e719

Hopefully you can see from this video that I am manually refreshing the page after each update. 

# Todo

+ [ ] Refresh the `timer` in the client when `timer.start` is updated to reflect the actual time elapsed. 

@LuchoTurtle please LMK if this is clear. 🙏

**Comment by LuchoTurtle** [comment]
I've tried fixing this but I can't seem to pinpoint where the issue is. 

When I update the timer that is *not running*, the text shows **correctly**. However, as the issue states, this is not the case when the timer *is running*.

## `update` broadcast handler
The thing is, in both occasions, the payload is the same and calls the same functions, which yield the same result.

For example, in the `  def handle_info(%Broadcast{event: "update", payload: payload}, socket) do` function,
the `payload` and `isEditingItem` variables are the same on both occasions.

https://github.com/dwyl/mvp/blob/a54d652b4eb8b57aa3f157374e258152993503ee/lib/app_web/live/app_live.ex#L231-L268

So the issue *shouldn't* be here*.

## `update-item-timer` event handler

This is the function that is called when the person clicks on `Update` button. 
Similarly to the previous function, the payload of the changes are the same (`{:ok, list}`).

https://github.com/dwyl/mvp/blob/a54d652b4eb8b57aa3f157374e258152993503ee/lib/app_web/live/app_live.ex#L220-L223

This means that on both occasions the page should be updating the items properly and being refreshed. I can't seem to find the reason why it works on non-running timers and doesn't on running timers... 😞 .

I'll keep looking...

**Comment by nelsonic** [comment]
I think this is handled by Alpine.js in the front end based on the data defined by LiveView

**Comment by nelsonic** [comment]
We looked at https://alpinejs.dev/magics/watch
But it appears as though the _updated_ value of the `timer.start` is not updating ...

https://github.com/dwyl/mvp/blob/a54d652b4eb8b57aa3f157374e258152993503ee/lib/app_web/live/app_live.html.heex#L449-L452

**Comment by LuchoTurtle** [comment]
As @nelsonic, after pair-debugging on this issue, we've narrowed the issue down to `timer.start` not updating.

https://github.com/dwyl/mvp/blob/a54d652b4eb8b57aa3f157374e258152993503ee/lib/app_web/live/app_live.html.heex#L433-L452

Since *when the timer **is running***, `Alpine.js` takes over, this is why the timer text is not re-rendering when we're updating the timer. 

@SimonLab , since you have more experience with this than us, whenever you have 5 minutes and/or next standup, we can take a look together to get this sorted 😀

**Comment by LuchoTurtle** [comment]
What changes did you end up making? I was under the impression that the `setInterval` function pertained to just re-rendering the timer on a set interval to show the seconds go by, and not directly related to the issue at hand. 💭

**Comment by nelsonic** [comment]
Sorry to leave you in suspense. I've pushed the code. Was just making a better `GIF`:
![dwyl-mvp-running-timer-updated-when-timer-start-updated-better](https://github.com/dwyl/mvp/assets/194400/38eb20b9-a722-4ebe-924e-1dc7d0930e46)
